import {
    NAV_ITEM_TYPE_ITEM,
     NAV_ITEM_TYPE_COLLAPSE
} from '@/constants/navigation.constant'
import { SUPER_ADMIN, HUB_MANAGER, ACCOUNT_OFFICER, ASSISTANT_HUB_MANAGER, MAINTENANCE_STORE_OFFICER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'home',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [SUPER_ADMIN],
        subMenu: [],
    },
    {
        key: 'accountofficer',
        path: '/account-officer/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.accountofficer',
        icon: 'home',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ACCOUNT_OFFICER],
        subMenu: [],
    },
    {
        key: 'account-officer-orders',
        path: '/account-officer/orders',
        title: 'Orders',
        translateKey: 'nav.orders',
        icon: 'orders',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ACCOUNT_OFFICER],
        subMenu: [],
    },
    {
        key: 'b2b',
        path: '/b2b',
        title: 'Business (B2B) Customers',
        translateKey: 'nav.b2b',
        icon: 'customers',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ACCOUNT_OFFICER],
        subMenu: [],
    },
    {
        key: 'invoices',
        path: '/due-invoices',
        title: 'Due Invoices',
        translateKey: 'nav.invoices',
        icon: 'invoices',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ACCOUNT_OFFICER],
        subMenu: [],
    },
    {
        key: 'assets',
        path: '/assets',
        title: 'Assets at trigger Level',
        translateKey: 'nav.assets',
        icon: 'assets',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ACCOUNT_OFFICER],
        subMenu: [],
    },
    {
        key: 'account-officer-onboarding',
        path: '/account-officer/onboarding',
        title: 'Onboarding',
        translateKey: 'nav.onboarding',
        icon: 'onboarding',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ACCOUNT_OFFICER],
        subMenu: [],
    },
    {
        key: 'hubdashboard',
        path: '/hub-dashboard',
        title: 'Hub Dashboard',
        translateKey: 'nav.hubdashboard',
        icon: 'home',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [HUB_MANAGER],
        subMenu: [],
    },
    {
        key: 'hubs',
        path: '/hubs',
        title: 'Hubs',
        translateKey: 'nav.hubs',
        icon: 'hubs',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [SUPER_ADMIN],
        subMenu: [],
    },
    {
        key: 'cylindertracking',
        path: '/cylinder-tracking',
        title: 'Cylinder Tracking',
        translateKey: 'nav.cylindertracking',
        icon: 'gigasstove',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [SUPER_ADMIN],
        subMenu: [],
    },
    {
        key: 'orders',
        path: '/orders',
        title: 'Stock Orders',
        translateKey: 'nav.orders',
        icon: 'orders',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [HUB_MANAGER, SUPER_ADMIN],
        subMenu: [],
    },
    {
        key: 'customers',
        path: '/customers',
        title: 'Customers',
        translateKey: 'nav.customers',
        icon: 'customers',
        subIcon:'',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [HUB_MANAGER,SUPER_ADMIN],
        subMenu: [ {
            key: 'homeuse',
            path: '/customers/b2c',
            title: 'Home Use (B2C)',
            translateKey: 'nav.homeuse',
            icon: '',
            subIcon:'homeuse',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [HUB_MANAGER,SUPER_ADMIN ],
            subMenu: [],
        },
        {
            key: 'business',
            path: '/customers/b2b',
            title: `Business (B2B)`,
            translateKey: 'nav.business',
            icon: '',
            subIcon:'business',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [HUB_MANAGER,SUPER_ADMIN],
            subMenu: [],
        },],
    },
    {
        key: 'accounting',
        path: '/accounting',
        title: 'Accounting',
        translateKey: 'nav.accounting',
        icon: 'accounting',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [HUB_MANAGER],
        subMenu: [],
    },
    {
        key: 'hubemployees',
        path: '/hub-employees',
        title: 'Hub Employees',
        translateKey: 'nav.storeemployees',
        icon: 'employees',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [HUB_MANAGER],
        subMenu: [],
    },
    {
        key: 'onboarding',
        path: '/onboarding',
        title: 'Onboarding',
        translateKey: 'nav.onboarding',
        icon: 'onboarding',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [HUB_MANAGER],
        subMenu: [],
    },
    {
        key: 'instock',
        path: '/instock',
        title: 'In-stock',
        translateKey: 'nav.instock',
        icon: 'instock',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [HUB_MANAGER],
        subMenu: [],
    },
    // {
    //     key: 'resolution',
    //     path: '/resolution',
    //     title: 'Resolution',
    //     translateKey: 'nav.resolution',
    //     icon: 'resolution',
    //     subIcon:'',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [USER],
    //     subMenu: [],
    // },
    // {
    //     key: 'emergency',
    //     path: '/emergency',
    //     title: 'Emergency',
    //     translateKey: 'nav.emergency',
    //     icon: 'emergency',
    //     subIcon:'',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [USER],
    //     subMenu: [],
    // },
    {
        key: 'settings',
        path: '/settings',
        title: 'Settings',
        translateKey: 'nav.settings',
        icon: 'settings',
        subIcon:'',

        type: NAV_ITEM_TYPE_ITEM,
        authority: [SUPER_ADMIN],
        subMenu: [],
    },
    {
        key: 'stocks',
        path: '/stocks',
        title: 'In-Stock',
        translateKey: 'nav.hubAssistance',
        icon: 'instock',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ASSISTANT_HUB_MANAGER],
        subMenu: [],
    },
    {
        key: 'maintenancedashboard',
        path: '/maintenance-dashboard',
        title: 'Dashboard',
        translateKey: 'nav.maintenancedashboard',
        icon: 'instock',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [MAINTENANCE_STORE_OFFICER],
        subMenu: [],
    },
    {
        key: 'cylindersonboarded',
        path: '/cylinders-onboarded',
        title: 'Cylinders Onboarded',
        translateKey: 'nav.maintenancedashboard',
        icon: 'onboarding',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [MAINTENANCE_STORE_OFFICER],
        subMenu: [],
    },
    {
        key: 'smartdevices',
        path: '/smart-devices-onboarded',
        title: 'Smart Devices',
        translateKey: 'nav.smartdevices',
        icon: 'instock',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [MAINTENANCE_STORE_OFFICER],
        subMenu: [],
    },
    {
        key: 'maintenanceonboarding',
        path: '/maintenace-onboarding',
        title: 'Onboarding',
        translateKey: 'nav.maintenanceonboarding',
        icon: 'onboarding',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [MAINTENANCE_STORE_OFFICER],
        subMenu: [],
    },
    {
        key: 'maintenanceinstock',
        path: '/maintenance-instock',
        title: 'In-stock',
        translateKey: 'nav.maintenanceinstock',
        icon: 'instock',
        subIcon:'',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [MAINTENANCE_STORE_OFFICER],
        subMenu: [],
    },



]

export default navigationConfig
